language: csharp

sudo: required

mono:
  - latest

solution: Solutions/IronPython.sln

install:
  - sudo apt-get install -y binfmt-support libmono-system-windows-forms4.0-cil
  - nuget restore Solutions/IronPython.sln

script:
  #- make ironpython-release
  - xbuild Build.proj /t:Build "/p:Mono=true;BaseConfiguration=Release"

after_script:
  #- make test-ipy-release
  - xbuild Test/TestRunner/TestRunner.sln /p:Configuration=Release
  - CONFIGURATION=Release DLR_ROOT=`pwd` DLR_BIN=`pwd`bin/%CONFIGURATION% mono Test/TestRunner/TestRunner/bin/%CONFIGURATION%/TestRunner.exe Test/IronPython.tests /verbose /binpath:bin/%CONFIGURATION% /all

notifications:
  email:
    recipients:
      #- slide.o.mix@gmail.com
      - ticotimo@gmail.com
    on_success: always # default: change
    #on_failure: [always|never|change] # default: always

