language: csharp

solution: Solutions/IronPython.sln

script:
  - make ironpython-release

after_script:
  - make test-ipy-release

notifications:
  email:
    recipients:
      #- slide.o.mix@gmail.com
      - ticotimo@gmail.com
    on_success: always # default: change
    #on_failure: [always|never|change] # default: always
